-- Schema para Supabase (Postgres) — Café & Barista Shop
-- Ejecútalo en Supabase Dashboard > SQL Editor > New query > Run
-- Es idempotente: puedes correrlo varias veces.

create table if not exists products (
  id integer generated by default as identity primary key,
  nombre varchar(200) not null,
  slug varchar(200) not null unique,
  descripcion text not null default '',
  descripcion_corta varchar(300) not null default '',
  precio integer not null,
  imagen varchar(500) not null default '',
  categoria varchar(50) not null default 'utensilios',
  destacado boolean not null default false,
  stock boolean not null default true,
  created_at timestamptz not null default now()
);
create index if not exists ix_products_slug on products (slug);
create index if not exists ix_products_categoria on products (categoria);
create index if not exists ix_products_destacado on products (destacado);

create table if not exists orders (
  id integer generated by default as identity primary key,
  customer_name varchar(200) not null default '',
  customer_email varchar(200) not null default '',
  customer_phone varchar(50) not null default '',
  shipping_name varchar(200) not null default '',
  shipping_address text not null default '',
  shipping_city varchar(100) not null default '',
  shipping_phone varchar(50) not null default '',
  shipping_notes text not null default '',
  total integer not null default 0,
  status varchar(50) not null default 'Pendiente',
  payment_id varchar(200) not null default '',
  preference_id varchar(200) not null default '',
  created_at timestamptz not null default now()
);
create index if not exists ix_orders_status on orders (status);
create index if not exists ix_orders_created_at on orders (created_at desc);

create table if not exists order_items (
  id integer generated by default as identity primary key,
  order_id integer references orders(id) on delete cascade,
  product_id integer,
  product_name varchar(200),
  cantidad integer not null default 1,
  precio integer not null default 0
);

-- RLS: como la app usa service-role / connection string directa (server-side),
-- no se necesitan policies públicas. Si activas RLS, crea policies o el backend fallará.
-- alter table products enable row level security;  -- NO activar sin policies
